name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    outputs:
      version: ${{ steps.set_output.outputs.version }}

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'
          cache: true

      - name: Build Windows Binary
        run: go build -ldflags="-X github.com/majd/ipatool/v2/cmd.version=$VERSION" -o ipatool-${{ needs.get_version.outputs.version }}-windows-${{ matrix.arch }}.exe
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          VERSION: ${{ needs.get_version.outputs.version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipatool-${{ needs.get_version.outputs.version }}-windows-${{ matrix.arch }}.exe
          path: ipatool-${{ needs.get_version.outputs.version }}-windows-${{ matrix.arch }}.exe
          if-no-files-found: error
